In [4]:
import os
import numpy as np
import pandas as pd

In [5]:
movies = pd.read_csv(r'tmdb_5000_movies.csv')
credits = pd.read_csv(r'tmdb_5000_credits.csv')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.shape

(4803, 20)

In [9]:
credits.shape

(4803, 4)

In [10]:
#let's Merge the two dataset on the basis of title

In [11]:
movies = movies.merge(credits,on='title')
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [12]:
movies.shape

(4809, 23)

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 619.9+ KB

In [14]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

The all feature we will not remove because these features are related to Recommendation Engine/System :

#Genres
#Id
#Keywords
#title: will remove original title (if it's should be local or any other)
#Overviews
#Cast
#Crew

In [15]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [18]:
#We got 3 misssing values in Overview column

In [19]:
movies.dropna(inplace=True) #Here we have to remove the missing values in overall datframe 
movies

<ipython-input-19-e4934092c855>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True) #Here we have to remove the missing values in overall datframe

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [20]:
movies.duplicated().sum() #To check have any duplicate row is present or not

0

In [21]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [22]:
#We have to make the list of this format

#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#A list form: ['Action', 'Adventure', 'Fantasy', 'SciFi']

In [23]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [24]:
# Now use the "ast" function to converte the string of list into a single list

In [25]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [26]:
movies['genres'] = movies['genres'].apply(convert) #Now I've getting list of all genres

<ipython-input-26-81bb2b0f8cff>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(convert) #Now I've getting list of all genres

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
movies['keywords'] = movies['keywords'].apply(convert) #Now I've getting list of all keywords

<ipython-input-28-6f3561194db9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(convert) #Now I've getting list of all keywords

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
import ast

In [31]:
def convert3(obj):
    l=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [32]:
movies['cast']=movies['cast'].apply(convert3)

<ipython-input-32-f7f209af84d8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convert3)

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [34]:
def only_director(obj):
    l=[]
    counter = 0
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
            l.append(i['name'])
            counter += 1
            break
    return l

In [35]:
movies['crew'] = movies['crew'].apply(only_director)
movies.head()

<ipython-input-35-a13fe5de204c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(only_director)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [36]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

#Now this string have to convert into list for perticular rows

In [37]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [38]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.head()

<ipython-input-38-fa93b4fd6aa2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview'] = movies['overview'].apply(lambda x:x.split())

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [39]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])

movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])

movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

movies

<ipython-input-39-9f420ecd3d11>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
<ipython-input-39-9f420ecd3d11>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
<ipython-input-39-9f420ecd3d11>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
<ipython-input-39-9f420ecd3d11>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [40]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [41]:
# Now use "Concatenation" function to make new column as name is "tags"

In [42]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies

<ipython-input-42-7d92073b915d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [43]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [44]:
#Here we have to make new DataFrame and remove the other unnecessary column

In [45]:
df = movies[['movie_id', 'title', 'tags']]
df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [46]:
#Now we got a three column as movie_id, title and tags
#but we got tags in the form of list 

# So now we have to convert a list words into a proper string

In [47]:
df['tags'] = df['tags'].apply(lambda x:" ".join(x))
df

<ipython-input-47-24eeaf3be67c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:" ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [48]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [49]:
#Now we have tags in the contents of 'overview','genres','keywords','cast','crew' in the form of proper list

In [50]:
#As recommendation system we have to convert a strings of tags column in 'lowercase', (as we know the all tags are containing in the form of lowecases)

In [51]:
df['tags'] = df['tags'].apply(lambda x:x.lower())
df

<ipython-input-51-0b1722d3bda9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

Now we have to do "Text-Vectorization"
    
First Step:    

Now we have converting a text into vector and then try to find a similarities between two vectors.

Then remove the stopwords from the list

in the "tags" feature, There is  number of similar words like- 'big','bigger','biggest'
so the stemming function is convert it into a single word that is "big" only.

So for that we will use NLTK library

In [52]:
import nltk

In [53]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [54]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [55]:
df['tags'] = df['tags'].apply(stem)
df['tags']

<ipython-input-55-0742b39f13a5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [56]:
df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [57]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [58]:
vectors = cv.fit_transform(df['tags']).toarray()

vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [59]:
vectors.shape

(4806, 5000)

In [60]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

Now we have to calculate the distance between the vectors in "5000 dimensional space" for that measurement we will use "Cosine Function" instead of "Euclidean Distance"


In high dimensional Euclidean distance is not good measure to be calculation.

At high dimensions, Euclidean distance loses pretty much all meaning.

In [62]:
from sklearn.metrics.pairwise import cosine_similarity

In [63]:
similarity = cosine_similarity(vectors) #pass the all vectors here
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [64]:
similarity.shape

(4806, 4806)

In [65]:
#This is first array of similarity
#You can see this is similarity of "all" movies with "first" movie

In [66]:
similarity[0] #As an similarity the score will be 1

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

Now we have to create one function, according to that function on movie the function will recommend you a 5 similar movies.

Steps Performing:

Step1: first we have to find the index of that given movie.

Step2: Then according to that index the function will cames into the similarity matrix (above mentions function) and took out that perticular index of movie.


Step3: Then according to that index we got the similaraties and we have to sort the distance of similarities.

Step4: After applied sorting function we got "More similar movies" in Beginning and "Less similar movies" in Ending.

And when we do sorting the elements of list are spread randomly, So that the index position will lose

Step5: So for that problem we have to grab the index of movie (Creat the index position according to distance) so for that we will use "Enumerate function"

Step6: According to the steps we will use Enumerate function and then we follow the process of sorting.


Step5: Then the recommend function fetch the "Top 5" movies from that list and recommend to user.

Now you can see the list of touple below i.e. shown the vectordistances of movies 1st, 2nd, 3rd and so on.....

In [67]:
(list(enumerate(similarity[0])))

[(0, 1.0000000000000002),
 (1, 0.08346223261119858),
 (2, 0.08603090020146065),
 (3, 0.0734718358370645),
 (4, 0.1892994097121204),
 (5, 0.10838874619051501),
 (6, 0.04024218182927669),
 (7, 0.14673479641335554),
 (8, 0.05923488777590923),
 (9, 0.0967301666813349),
 (10, 0.10259783520851541),
 (11, 0.09464970485606021),
 (12, 0.09037128496931669),
 (13, 0.04499212706658476),
 (14, 0.12824729401064427),
 (15, 0.06282808624375433),
 (16, 0.07894736842105264),
 (17, 0.13977653617040256),
 (18, 0.09493290614465533),
 (19, 0.0830812984794528),
 (20, 0.058038100008800934),
 (21, 0.10968169942141635),
 (22, 0.0662266178532522),
 (23, 0.08740748201220976),
 (24, 0.0533380747062665),
 (25, 0.05101627678885769),
 (26, 0.15389675281277312),
 (27, 0.18693292157876878),
 (28, 0.116543309349613),
 (29, 0.065033247714309),
 (30, 0.06684847767323797),
 (31, 0.15907119074394446),
 (32, 0.08520286456846099),
 (33, 0.09733285267845754),
 (34, 0.0),
 (35, 0.09933992677987831),
 (36, 0.17316974359835272),
 (37, 0.07894736842105264),
 (38, 0.08111071056538127),
 (39, 0.08226127456606226),
 (40, 0.07694837640638656),
 (41, 0.16563698349810535),
 (42, 0.0),
 (43, 0.09086217008485092),
 (44, 0.03382550457458692),
 (45, 0.08240856434303293),
 (46, 0.1391037210186643),
 (47, 0.19672236884115843),
 (48, 0.08447772061910234),
 (49, 0.0582716546748065),
 (50, 0.11295649894498103),
 (51, 0.08048436365855338),
 (52, 0.14843120879858804),
 (53, 0.042973504259354006),
 (54, 0.031219527052723135),
 (55, 0.07038153430777869),
 (56, 0.13834289277321493),
 (57, 0.024182541670333724),
 (58, 0.06748819059987714),
 (59, 0.07254762501100116),
 (60, 0.018367958959266125),
 (61, 0.23179316248638276),
 (62, 0.0837707816583391),
 (63, 0.08175191193132876),
 (64, 0.029617443887954616),
 (65, 0.019529164171612674),
 (66, 0.02249606353329238),
 (67, 0.16452254913212452),
 (68, 0.1204950466257556),
 (69, 0.02649064714130088),
 (70, 0.076004188790721),
 (71, 0.07336739820667779),
 (72, 0.13710212427677043),
 (73, 0.0331133089266261),
 (74, 0.2024645717996314),
 (75, 0.10390486669322622),
 (76, 0.07175473098524099),
 (77, 0.014394823400711486),
 (78, 0.050669459193814),
 (79, 0.0623109738595896),
 (80, 0.050464733268936676),
 (81, 0.11020775375559676),
 (82, 0.076004188790721),
 (83, 0.17996850826633903),
 (84, 0.12361284651454937),
 (85, 0.1141270638770543),
 (86, 0.07098727864204515),
 (87, 0.11128297681493143),
 (88, 0.09037128496931669),
 (89, 0.05757929360284594),
 (90, 0.06131393394849658),
 (91, 0.16692446522239718),
 (92, 0.0623109738595896),
 (93, 0.07098727864204515),
 (94, 0.1873171623163388),
 (95, 0.14048787173725413),
 (96, 0.07694837640638656),
 (97, 0.06952346619889824),
 (98, 0.07509392614826384),
 (99, 0.02666903735313325),
 (100, 0.06765100914917384),
 (101, 0.07694837640638656),
 (102, 0.12462194771917919),
 (103, 0.07987230638308718),
 (104, 0.05564148840746572),
 (105, 0.1037571695799112),
 (106, 0.0623109738595896),
 (107, 0.061806423257274694),
 (108, 0.14509525002200235),
 (109, 0.06488856845230502),
 (110, 0.04499212706658476),
 (111, 0.15018785229652767),
 (112, 0.07694837640638656),
 (113, 0.043355498476206004),
 (114, 0.04588314677411236),
 (115, 0.043747863925980714),
 (116, 0.04836508334066745),
 (117, 0.05923488777590923),
 (118, 0.03364315551262445),
 (119, 0.043355498476206004),
 (120, 0.0),
 (121, 0.11128297681493143),
 (122, 0.116543309349613),
 (123, 0.1124803176664619),
 (124, 0.06748819059987714),
 (125, 0.07843304784240032),
 (126, 0.13334518676566626),
 (127, 0.14601068654819693),
 (128, 0.0),
 (129, 0.09269795493186431),
 (130, 0.027036903521793755),
 (131, 0.10526315789473685),
 (132, 0.04499212706658476),
 (133, 0.028239124736245257),
 (134, 0.12977713690461004),
 (135, 0.0),
 (136, 0.023414645289542353),
 (137, 0.0301237616564389),
 (138, 0.12824729401064427),
 (139, 0.12072654548783007),
 (140, 0.04499212706658476),
 (141, 0.08740748201220976),
 (142, 0.08471737420873576),
 (143, 0.08671099695241201),
 (144, 0.05006261743217589),
 (145, 0.019252140716412975),
 (146, 0.016303866268150616),
 (147, 0.05564148840746572),
 (148, 0.09733285267845754),
 (149, 0.15511334686589626),
 (150, 0.16426202236672155),
 (151, 0.2029530274475215),
 (152, 0.08346223261119858),
 (153, 0.07868894753646337),
 (154, 0.06131393394849658),
 (155, 0.02043797798283219),
 (156, 0.05990422978731538),
 (157, 0.09933992677987831),
 (158, 0.13369695534647594),
 (159, 0.06362847629757779),
 (160, 0.11712303424679457),
 (161, 0.03181423814878889),
 (162, 0.0331133089266261),
 (163, 0.050669459193814),
 (164, 0.08000711205939975),
 (165, 0.04588314677411236),
 (166, 0.12515654358043973),
 (167, 0.09037128496931669),
 (168, 0.17521916101261562),
 (169, 0.08830215713766959),
 (170, 0.10650358071057624),
 (171, 0.02271554252121273),
 (172, 0.21239769762143662),
 (173, 0.023174488732966077),
 (174, 0.07792865001991967),
 (175, 0.07098727864204515),
 (176, 0.02913582733740325),
 (177, 0.0),
 (178, 0.024455799402225926),
 (179, 0.07254762501100116),
 (180, 0.022075539284417398),
 (181, 0.04499212706658476),
 (182, 0.11707322644771176),
 (183, 0.07038153430777869),
 (184, 0.177343107178349),
 (185, 0.050669459193814),
 (186, 0.05901671065234752),
 (187, 0.15389675281277312),
 (188, 0.022075539284417398),
 (189, 0.1147078669352809),
 (190, 0.08447772061910234),
 (191, 0.04891159880445185),
 (192, 0.047324852428030105),
 (193, 0.07878168645790681),
 (194, 0.0),
 (195, 0.05923488777590923),
 (196, 0.05195243334661311),
 (197, 0.036973693332326786),
 (198, 0.057353933467640436),
 (199, 0.08671099695241201),
 (200, 0.10882143751650175),
 (201, 0.0),
 (202, 0.031219527052723135),
 (203, 0.08346223261119858),
 (204, 0.04947706959952935),
 (205, 0.07443229275647868),
 (206, 0.11092107999698035),
 (207, 0.07694837640638656),
 (208, 0.12262786789699316),
 (209, 0.06765100914917384),
 (210, 0.07509392614826384),
 (211, 0.024455799402225926),
 (212, 0.06622661785325219),
 (213, 0.05901671065234752),
 (214, 0.0),
 (215, 0.06622661785325219),
 (216, 0.06488856845230502),
 (217, 0.08520286456846099),
 (218, 0.03823595564509363),
 (219, 0.09197090092274487),
 (220, 0.1777046633277277),
 (221, 0.047324852428030105),
 (222, 0.07987230638308718),
 (223, 0.10390486669322622),
 (224, 0.060833032924035954),
 (225, 0.046829290579084706),
 (226, 0.0301237616564389),
 (227, 0.08226127456606226),
 (228, 0.11037769642208699),
 (229, 0.1074861545850028),
 (230, 0.09183979479633063),
 (231, 0.0),
 (232, 0.11128297681493143),
 (233, 0.1037571695799112),
 (234, 0.08594700851870801),
 (235, 0.076004188790721),
 (236, 0.11470786693528087),
 (237, 0.0662266178532522),
 (238, 0.11092107999698035),
 (239, 0.09125667909262308),
 (240, 0.046829290579084706),
 (241, 0.07894736842105264),
 (242, 0.08111071056538127),
 (243, 0.09269795493186431),
 (244, 0.09197090092274487),
 (245, 0.08111071056538127),
 (246, 0.07594632491572426),
 (247, 0.0),
 (248, 0.04456565178215865),
 (249, 0.13834289277321493),
 (250, 0.0),
 (251, 0.04188539082916955),
 (252, 0.020277677641345318),
 (253, 0.06282808624375433),
 (254, 0.06952346619889824),
 (255, 0.0),
 (256, 0.11164843913471803),
 (257, 0.0533380747062665),
 (258, 0.01769980813511972),
 (259, 0.06131393394849658),
 (260, 0.20395079136182276),
 (261, 0.024182541670333724),
 (262, 0.10650358071057624),
 (263, 0.09733285267845754),
 (264, 0.0),
 (265, 0.02742042485535409),
 (266, 0.0989541391990587),
 (267, 0.06488856845230502),
 (268, 0.052631578947368425),
 (269, 0.029617443887954616),
 (270, 0.08830215713766959),
 (271, 0.07098727864204515),
 (272, 0.02782074420373286),
 (273, 0.021119430154775586),
 (274, 0.08977310580745099),
 (275, 0.1433848336691011),
 (276, 0.06243905410544627),
 (277, 0.053099424405359155),
 (278, 0.11707322644771176),
 (279, 0.09269795493186431),
 (280, 0.0),
 (281, 0.065033247714309),
 (282, 0.04456565178215865),
 (283, 0.02742042485535409),
 (284, 0.018367958959266125),
 (285, 0.019529164171612674),
 (286, 0.0781166566864507),
 (287, 0.025976216673306556),
 (288, 0.02742042485535409),
 (289, 0.04588314677411236),
 (290, 0.06362847629757779),
 (291, 0.05006261743217589),
 (292, 0.08885233166386385),
 (293, 0.029617443887954616),
 (294, 0.1433848336691011),
 (295, 0.10526315789473685),
 (296, 0.038778336716474064),
 (297, 0.044151078568834795),
 (298, 0.0),
 (299, 0.05945550264670635),
 (300, 0.1711905958155815),
 (301, 0.09365858115816939),
 (302, 0.06952346619889824),
 (303, 0.02782074420373286),
 (304, 0.06578947368421054),
 (305, 0.19007487139298027),
 (306, 0.08111071056538127),
 (307, 0.10876595882948199),
 (308, 0.06765100914917384),
 (309, 0.06243905410544627),
 (310, 0.03065696697424829),
 (311, 0.15018785229652765),
 (312, 0.10012523486435178),
 (313, 0.05484084971070818),
 (314, 0.0),
 (315, 0.08346223261119858),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09933992677987831),
 (320, 0.03065696697424829),
 (321, 0.0),
 (322, 0.2105263157894737),
 (323, 0.029617443887954616),
 (324, 0.024455799402225926),
 (325, 0.09933992677987831),
 (326, 0.05647824947249051),
 (327, 0.027036903521793755),
 (328, 0.02742042485535409),
 (329, 0.07894736842105264),
 (330, 0.10012523486435178),
 (331, 0.08998425413316952),
 (332, 0.106676149412533),
 (333, 0.024455799402225926),
 (334, 0.0967301666813349),
 (335, 0.046348977465932154),
 (336, 0.06917144638660747),
 (337, 0.04543108504242546),
 (338, 0.0),
 (339, 0.04891159880445185),
 (340, 0.04947706959952935),
 (341, 0.08226127456606226),
 (342, 0.16122923187750418),
 (343, 0.019252140716412975),
 (344, 0.029617443887954616),
 (345, 0.02294157338705618),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06131393394849658),
 (349, 0.076004188790721),
 (350, 0.04891159880445185),
 (351, 0.0),
 (352, 0.02742042485535409),
 (353, 0.04120428217151646),
 (354, 0.021677749238103002),
 (355, 0.03650267163704923),
 (356, 0.09037128496931669),
 (357, 0.0),
 (358, 0.0602475233128778),
 (359, 0.031219527052723135),
 (360, 0.020942695414584774),
 (361, 0.07509392614826384),
 (362, 0.09544271444636668),
 (363, 0.09909250441117726),
 (364, 0.023414645289542353),
 (365, 0.07509392614826384),
 (366, 0.05647824947249051),
 (367, 0.0),
 (368, 0.12977713690461004),
 (369, 0.12824729401064427),
 (370, 0.050669459193814),
 (371, 0.09567297464698798),
 (372, 0.047324852428030105),
 (373, 0.17292861596651865),
 (374, 0.03797316245786213),
 (375, 0.061313933948496574),
 (376, 0.046829290579084706),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05073825686188038),
 (380, 0.05195243334661311),
 (381, 0.0837707816583391),
 (382, 0.0),
 (383, 0.043355498476206004),
 (384, 0.028676966733820218),
 (385, 0.0),
 (386, 0.021873931962990357),
 (387, 0.023662426214015053),
 (388, 0.0),
 (389, 0.08740748201220976),
 (390, 0.026315789473684213),
 (391, 0.056573571480353566),
 (392, 0.0301237616564389),
 (393, 0.0),
 (394, 0.024738534799764674),
 (395, 0.0533380747062665),
 (396, 0.043747863925980714),
 (397, 0.05195243334661311),
 (398, 0.0),
 (399, 0.023662426214015053),
 (400, 0.09037128496931669),
 (401, 0.031219527052723135),
 (402, 0.07792865001991967),
 (403, 0.0830812984794528),
 (404, 0.06131393394849658),
 (405, 0.05564148840746572),
 (406, 0.0207703246198632),
 (407, 0.021300716142115247),
 (408, 0.03244428422615251),
 (409, 0.0),
 (410, 0.0978231976089037),
 (411, 0.052631578947368425),
 (412, 0.09567297464698798),
 (413, 0.1411956236812263),
 (414, 0.029617443887954616),
 (415, 0.053418342734682205),
 (416, 0.050669459193814),
 (417, 0.03244428422615251),
 (418, 0.03539961627023944),
 (419, 0.06882472016116853),
 (420, 0.1124803176664619),
 (421, 0.023174488732966077),
 (422, 0.116543309349613),
 (423, 0.04120428217151646),
 (424, 0.03721614637823934),
 (425, 0.06390214842634574),
 (426, 0.05374307729250139),
 (427, 0.026315789473684213),
 (428, 0.055824219567359015),
 (429, 0.0),
 (430, 0.050669459193814),
 (431, 0.024182541670333724),
 (432, 0.11357771260606365),
 (433, 0.031219527052723135),
 (434, 0.0),
 (435, 0.03539961627023944),
 (436, 0.0),
 (437, 0.025649458802128853),
 (438, 0.12227899701112963),
 (439, 0.026315789473684213),
 (440, 0.024738534799764674),
 (441, 0.057353933467640436),
 (442, 0.04543108504242546),
 (443, 0.06390214842634574),
 (444, 0.0),
 (445, 0.0989541391990587),
 (446, 0.023174488732966077),
 (447, 0.06446025638903101),
 (448, 0.021300716142115247),
 (449, 0.10968169942141635),
 (450, 0.021300716142115247),
 (451, 0.025031308716087945),
 (452, 0.03065696697424829),
 (453, 0.024455799402225926),
 (454, 0.11707322644771176),
 (455, 0.060833032924035954),
 (456, 0.043355498476206004),
 (457, 0.08603090020146065),
 (458, 0.043355498476206004),
 (459, 0.03458572319330373),
 (460, 0.024182541670333724),
 (461, 0.1411956236812263),
 (462, 0.032283269414765066),
 (463, 0.03244428422615251),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14509525002200233),
 (467, 0.10559715077387793),
 (468, 0.02782074420373286),
 (469, 0.05945550264670635),
 (470, 0.04543108504242546),
 (471, 0.06390214842634574),
 (472, 0.106676149412533),
 (473, 0.09269795493186431),
 (474, 0.0),
 (475, 0.043747863925980714),
 (476, 0.13530201829834768),
 (477, 0.0),
 (478, 0.05407380704358751),
 (479, 0.08797691788472337),
 (480, 0.0978231976089037),
 (481, 0.0),
 (482, 0.021873931962990357),
 (483, 0.12487810821089254),
 (484, 0.02913582733740325),
 (485, 0.052631578947368425),
 (486, 0.07992075789278003),
 (487, 0.12725695259515557),
 (488, 0.06657426652986062),
 (489, 0.0),
 (490, 0.14159846508095775),
 (491, 0.09909250441117726),
 (492, 0.076004188790721),
 (493, 0.03065696697424829),
 (494, 0.0),
 (495, 0.19088542889273336),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06765100914917384),
 (499, 0.0),
 (500, 0.025976216673306556),
 (501, 0.08175191193132876),
 (502, 0.13369695534647594),
 (503, 0.07509392614826384),
 (504, 0.0),
 (505, 0.13530201829834768),
 (506, 0.03458572319330373),
 (507, 0.255608593705383),
 (508, 0.101338918387628),
 (509, 0.022075539284417398),
 (510, 0.0989541391990587),
 (511, 0.09197090092274487),
 (512, 0.02742042485535409),
 (513, 0.14843120879858804),
 (514, 0.04947706959952935),
 (515, 0.024738534799764674),
 (516, 0.028239124736245257),
 (517, 0.0),
 (518, 0.043747863925980714),
 (519, 0.0),
 (520, 0.0),
 (521, 0.025031308716087945),
 (522, 0.024182541670333724),
 (523, 0.04836508334066745),
 (524, 0.0),
 (525, 0.047324852428030105),
 (526, 0.028239124736245257),
 (527, 0.0331133089266261),
 (528, 0.022282825891079324),
 (529, 0.16742770563222897),
 (530, 0.05564148840746572),
 (531, 0.046348977465932154),
 (532, 0.021300716142115247),
 (533, 0.0602475233128778),
 (534, 0.0837707816583391),
 (535, 0.0978231976089037),
 (536, 0.1124803176664619),
 (537, 0.06765100914917384),
 (538, 0.0),
 (539, 0.25038669783359574),
 (540, 0.07509392614826384),
 (541, 0.10559715077387793),
 (542, 0.036973693332326786),
 (543, 0.07098727864204515),
 (544, 0.05564148840746572),
 (545, 0.024738534799764674),
 (546, 0.06362847629757779),
 (547, 0.08346223261119858),
 (548, 0.0),
 (549, 0.11959121830873498),
 (550, 0.024738534799764674),
 (551, 0.03771571432023571),
 (552, 0.0),
 (553, 0.028676966733820218),
 (554, 0.0),
 (555, 0.04499212706658475),
 (556, 0.02666903735313325),
 (557, 0.12227899701112963),
 (558, 0.0),
 (559, 0.0301237616564389),
 (560, 0.03604920469572501),
 (561, 0.03181423814878889),
 (562, 0.03065696697424829),
 (563, 0.025649458802128853),
 (564, 0.08885233166386385),
 (565, 0.043355498476206004),
 (566, 0.023918243661746996),
 (567, 0.025031308716087945),
 (568, 0.1411956236812263),
 (569, 0.047324852428030105),
 (570, 0.06765100914917384),
 (571, 0.04223886030955117),
 (572, 0.10743376064838502),
 (573, 0.0207703246198632),
 (574, 0.023414645289542353),
 (575, 0.04543108504242546),
 (576, 0.05195243334661311),
 (577, 0.1976738731537168),
 (578, 0.037463432463267755),
 (579, 0.14567913668701626),
 (580, 0.024182541670333724),
 (581, 0.14567913668701626),
 (582, 0.24511108480187255),
 (583, 0.03771571432023571),
 (584, 0.08111071056538127),
 (585, 0.024455799402225926),
 (586, 0.04499212706658476),
 (587, 0.09464970485606021),
 (588, 0.025649458802128853),
 (589, 0.1163350101494222),
 (590, 0.0301237616564389),
 (591, 0.06282808624375433),
 (592, 0.021119430154775586),
 (593, 0.0),
 (594, 0.04947706959952935),
 (595, 0.16059101370939324),
 (596, 0.09269795493186431),
 (597, 0.05923488777590923),
 (598, 0.03627381250550058),
 (599, 0.02742042485535409),
 (600, 0.06882472016116853),
 (601, 0.033463724070512735),
 (602, 0.09086217008485092),
 (603, 0.05407380704358751),
 (604, 0.0662266178532522),
 (605, 0.025031308716087945),
 (606, 0.0),
 (607, 0.05775642214923893),
 (608, 0.0),
 (609, 0.046829290579084706),
 (610, 0.058038100008800934),
 (611, 0.023174488732966077),
 (612, 0.06335829046432676),
 (613, 0.03539961627023944),
 (614, 0.04891159880445185),
 (615, 0.06131393394849658),
 (616, 0.03458572319330373),
 (617, 0.05006261743217589),
 (618, 0.08830215713766959),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06488856845230502),
 (622, 0.021119430154775586),
 (623, 0.0),
 (624, 0.1037571695799112),
 (625, 0.031219527052723135),
 (626, 0.08226127456606226),
 (627, 0.10882143751650175),
 (628, 0.0),
 (629, 0.04836508334066745),
 (630, 0.024455799402225926),
 (631, 0.050669459193814),
 (632, 0.07694837640638656),
 (633, 0.022282825891079324),
 (634, 0.07421560439929402),
 (635, 0.06622661785325219),
 (636, 0.023414645289542353),
 (637, 0.024182541670333724),
 (638, 0.03382550457458692),
 (639, 0.0),
 (640, 0.05990422978731538),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10012523486435178),
 (644, 0.05006261743217589),
 (645, 0.044151078568834795),
 (646, 0.052631578947368425),
 (647, 0.04836508334066745),
 (648, 0.0301237616564389),
 (649, 0.0),
 (650, 0.05195243334661311),
 (651, 0.0),
 (652, 0.042973504259354006),
 (653, 0.10882143751650175),
 (654, 0.10385162309931599),
 (655, 0.023918243661746996),
 (656, 0.0),
 (657, 0.03458572319330373),
 (658, 0.04836508334066745),
 (659, 0.025334729596907),
 (660, 0.09365858115816941),
 (661, 0.1675415633166782),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0602475233128778),
 (665, 0.06814662756363819),
 (666, 0.05006261743217589),
 (667, 0.0),
 (668, 0.13530201829834768),
 (669, 0.03539961627023944),
 (670, 0.01749278571353299),
 (671, 0.06814662756363819),
 (672, 0.028239124736245257),
 (673, 0.019968076595771794),
 (674, 0.07098727864204515),
 (675, 0.04499212706658476),
 (676, 0.028676966733820218),
 (677, 0.025031308716087945),
 (678, 0.116543309349613),
 (679, 0.0),
 (680, 0.07509392614826384),
 (681, 0.02742042485535409),
 (682, 0.019968076595771794),
 (683, 0.04836508334066745),
 (684, 0.0),
 (685, 0.03244428422615251),
 (686, 0.03181423814878889),
 (687, 0.10390486669322622),
 (688, 0.043355498476206004),
 (689, 0.0),
 (690, 0.025031308716087945),
 (691, 0.05923488777590923),
 (692, 0.10936965981495178),
 (693, 0.03382550457458692),
 (694, 0.021873931962990357),
 (695, 0.0662266178532522),
 (696, 0.021486752129677003),
 (697, 0.0),
 (698, 0.043355498476206004),
 (699, 0.03823595564509363),
 (700, 0.028676966733820218),
 (701, 0.057353933467640436),
 (702, 0.02249606353329238),
 (703, 0.021486752129677003),
 (704, 0.06814662756363819),
 (705, 0.024455799402225926),
 (706, 0.021677749238103002),
 (707, 0.0),
 (708, 0.024738534799764674),
 (709, 0.02060214108575823),
 (710, 0.05775642214923893),
 (711, 0.052631578947368425),
 (712, 0.0),
 (713, 0.024738534799764674),
 (714, 0.0),
 (715, 0.09933992677987831),
 (716, 0.027036903521793755),
 (717, 0.0),
 (718, 0.04499212706658476),
 (719, 0.0),
 (720, 0.026315789473684213),
 (721, 0.03244428422615251),
 (722, 0.0),
 (723, 0.024455799402225926),
 (724, 0.023662426214015053),
 (725, 0.0),
 (726, 0.0),
 (727, 0.030794751789719334),
 (728, 0.07254762501100118),
 (729, 0.04891159880445185),
 (730, 0.030254451040802585),
 (731, 0.05195243334661311),
 (732, 0.06814662756363819),
 (733, 0.061313933948496574),
 (734, 0.06684847767323797),
 (735, 0.06684847767323797),
 (736, 0.029617443887954616),
 (737, 0.07694837640638656),
 (738, 0.0),
 (739, 0.03823595564509363),

In [68]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])

#So now you can see the similarity in vectors or in movies (In the beginning there are the similar movies)

[(0, 1.0000000000000002),
 (1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574),
 (582, 0.24511108480187255),
 (1204, 0.24455799402225925),
 (1194, 0.2367785320221084),
 (61, 0.23179316248638276),
 (778, 0.23174488732966073),
 (4048, 0.2278389747471728),
 (1920, 0.2252817784447915),
 (2786, 0.21853668936906193),
 (172, 0.21239769762143662),
 (972, 0.2108663315950723),
 (322, 0.2105263157894737),
 (2333, 0.20443988269091456),
 (3608, 0.20437977982832192),
 (260, 0.20395079136182276),
 (151, 0.2029530274475215),
 (4192, 0.2029530274475215),
 (1444, 0.20277677641345318),
 (74, 0.2024645717996314),
 (1089, 0.2020475485519274),
 (3675, 0.1979082783981174),
 (973, 0.19767387315371682),
 (577, 0.1976738731537168),
 (47, 0.19672236884115843),
 (2971, 0.1925214071641298),
 (942, 0.19134594929397597),
 (495, 0.19088542889273336),
 (1201, 0.19088542889273336),
 (305, 0.19007487139298027),
 (4, 0.1892994097121204),
 (4405, 0.18731716231633883),
 (94, 0.1873171623163388),
 (27, 0.18693292157876878),
 (3327, 0.1860807318911967),
 (1275, 0.18394180184548975),
 (1329, 0.18394180184548975),
 (2999, 0.1813690625275029),
 (3999, 0.18074256993863339),
 (83, 0.17996850826633903),
 (1071, 0.17954621161490197),
 (220, 0.1777046633277277),
 (184, 0.177343107178349),
 (1321, 0.17699808135119718),
 (168, 0.17521916101261562),
 (2204, 0.17521916101261562),
 (4336, 0.17521916101261562),
 (931, 0.1748149640244195),
 (36, 0.17316974359835272),
 (373, 0.17292861596651865),
 (300, 0.1711905958155815),
 (3538, 0.1711905958155815),
 (3162, 0.17040572913692198),
 (1982, 0.16943474841747155),
 (661, 0.1675415633166782),
 (529, 0.16742770563222897),
 (1831, 0.16742770563222897),
 (91, 0.16692446522239718),
 (41, 0.16563698349810535),
 (67, 0.16452254913212452),
 (150, 0.16426202236672155),
 (1537, 0.16222142113076254),
 (342, 0.16122923187750418),
 (595, 0.16059101370939324),
 (31, 0.15907119074394446),
 (2515, 0.15907119074394446),
 (1178, 0.15789473684210528),
 (4010, 0.15737789507292674),
 (2731, 0.15609763526361567),
 (149, 0.15511334686589626),
 (838, 0.1540171257313038),
 (26, 0.15389675281277312),
 (187, 0.15389675281277312),
 (1383, 0.152008377581442),
 (111, 0.15018785229652767),
 (1344, 0.15018785229652767),
 (311, 0.15018785229652765),
 (52, 0.14843120879858804),
 (513, 0.14843120879858804),
 (2075, 0.14808721943977307),
 (7, 0.14673479641335554),
 (2760, 0.14659886790209342),
 (127, 0.14601068654819693),
 (579, 0.14567913668701626),
 (581, 0.14567913668701626),
 (108, 0.14509525002200235),
 (1297, 0.14509525002200235),
 (466, 0.14509525002200233),
 (1396, 0.14421498760030763),
 (1479, 0.1442149876003076),
 (1355, 0.14350946197048198),
 (1938, 0.14350946197048198),
 (275, 0.1433848336691011),
 (294, 0.1433848336691011),
 (3354, 0.1433848336691011),
 (1056, 0.1419745572840903),
 (1273, 0.1419745572840903),
 (490, 0.14159846508095775),
 (1488, 0.14159846508095775),
 (413, 0.1411956236812263),
 (461, 0.1411956236812263),
 (568, 0.1411956236812263),
 (2496, 0.1411956236812263),
 (95, 0.14048787173725413),
 (17, 0.13977653617040256),
 (46, 0.1391037210186643),
 (3409, 0.1391037210186643),
 (1965, 0.13872950617564817),
 (56, 0.13834289277321493),
 (249, 0.13834289277321493),
 (1327, 0.13834289277321493),
 (3781, 0.13834289277321493),
 (72, 0.13710212427677043),
 (843, 0.13710212427677043),
 (859, 0.13710212427677043),
 (2169, 0.13710212427677043),
 (4538, 0.13629325512727639),
 (476, 0.13530201829834768),
 (505, 0.13530201829834768),
 (668, 0.13530201829834768),
 (935, 0.13530201829834768),
 (3982, 0.13530201829834768),
 (1808, 0.13518451760896877),
 (4348, 0.13497638119975428),
 (1322, 0.13476498501489081),
 (158, 0.13369695534647594),
 (502, 0.13369695534647594),
 (777, 0.13369695534647594),
 (126, 0.13334518676566626),
 (1560, 0.13334518676566626),
 (1373, 0.1324532357065044),
 (2378, 0.1324532357065044),
 (2584, 0.1324532357065044),
 (4079, 0.13157894736842107),
 (2133, 0.13124359177794215),
 (1015, 0.12988108336653278),
 (2181, 0.12988108336653278),
 (3622, 0.12988108336653278),
 (134, 0.12977713690461004),
 (368, 0.12977713690461004),
 (1774, 0.12977713690461004),
 (2873, 0.12892051277806202),
 (14, 0.12824729401064427),
 (138, 0.12824729401064427),
 (369, 0.12824729401064427),
 (1086, 0.12824729401064427),
 (2686, 0.12824729401064427),
 (4230, 0.12824729401064427),
 (487, 0.12725695259515557),
 (773, 0.12725695259515557),
 (2970, 0.12725695259515557),
 (937, 0.126673647984535),
 (2480, 0.12565617248750865),
 (1741, 0.12565617248750863),
 (166, 0.12515654358043973),
 (754, 0.12515654358043973),
 (2450, 0.12515654358043973),
 (3628, 0.12515654358043973),
 (483, 0.12487810821089254),
 (1096, 0.12487810821089254),
 (1158, 0.12487810821089254),
 (2652, 0.12487810821089254),
 (102, 0.12462194771917919),
 (84, 0.12361284651454937),
 (208, 0.12262786789699316),
 (3376, 0.12262786789699316),
 (1878, 0.12262786789699313),
 (438, 0.12227899701112963),
 (557, 0.12227899701112963),
 (1299, 0.12227899701112963),
 (2331, 0.12166606584807191),
 (2674, 0.12166606584807191),
 (3083, 0.12166606584807191),
 (139, 0.12072654548783007),
 (68, 0.1204950466257556),
 (781, 0.1204950466257556),
 (1004, 0.1204950466257556),
 (1274, 0.1204950466257556),
 (1658, 0.1204950466257556),
 (1002, 0.11980845957463077),
 (549, 0.11959121830873498),
 (870, 0.11959121830873498),
 (900, 0.11959121830873498),
 (3235, 0.11959121830873498),
 (1047, 0.11846977555181847),
 (1833, 0.11846977555181847),
 (2060, 0.11846977555181847),
 (2741, 0.11846977555181847),
 (4673, 0.11846977555181847),
 (1673, 0.11803342130469505),
 (1715, 0.11803342130469505),
 (2789, 0.11803342130469505),
 (3721, 0.11803342130469505),
 (4000, 0.11803342130469505),
 (160, 0.11712303424679457),
 (182, 0.11707322644771176),
 (278, 0.11707322644771176),
 (454, 0.11707322644771176),
 (1617, 0.11707322644771176),
 (2284, 0.11707322644771176),
 (28, 0.116543309349613),
 (122, 0.116543309349613),
 (422, 0.116543309349613),
 (678, 0.116543309349613),
 (589, 0.1163350101494222),
 (2547, 0.11587244366483038),
 (1497, 0.11551284429847784),
 (3212, 0.11506355109724453),
 (189, 0.1147078669352809),
 (1220, 0.1147078669352809),
 (236, 0.11470786693528087),
 (1301, 0.11470786693528087),
 (85, 0.1141270638770543),
 (432, 0.11357771260606365),
 (1418, 0.11357771260606365),
 (50, 0.11295649894498103),
 (1616, 0.11295649894498103),
 (123, 0.1124803176664619),
 (420, 0.1124803176664619),
 (536, 0.1124803176664619),
 (889, 0.11243619908556624),
 (3147, 0.11239029738980327),
 (256, 0.11164843913471803),
 (808, 0.11164843913471803),
 (1348, 0.11164843913471803),
 (1575, 0.11164843913471803),
 (2372, 0.11141412945539662),
 (3309, 0.11141412945539662),
 (1512, 0.11141412945539661),
 (87, 0.11128297681493143),
 (121, 0.11128297681493143),
 (232, 0.11128297681493143),
 (4468, 0.11128297681493143),
 (206, 0.11092107999698035),
 (238, 0.11092107999698035),
 (228, 0.11037769642208699),
 (81, 0.11020775375559676),
 (1574, 0.11020775375559674),
 (3428, 0.10968169942141637),
 (21, 0.10968169942141635),
 (449, 0.10968169942141635),
 (1031, 0.10968169942141635),
 (1945, 0.10968169942141635),
 (2148, 0.10968169942141635),
 (3008, 0.10968169942141635),
 (692, 0.10936965981495178),
 (200, 0.10882143751650175),
 (627, 0.10882143751650175),
 (653, 0.10882143751650175),
 (1524, 0.10882143751650175),
 (307, 0.10876595882948199),
 (5, 0.10838874619051501),
 (3093, 0.10838874619051501),
 (3630, 0.10838874619051501),
 (740, 0.108388746190515),
 (786, 0.10814761408717502),
 (3498, 0.10814761408717502),
 (4777, 0.10814761408717502),
 (229, 0.1074861545850028),
 (572, 0.10743376064838502),
 (939, 0.1068366854693644),
 (332, 0.106676149412533),
 (472, 0.106676149412533),
 (1237, 0.106676149412533),
 (170, 0.10650358071057624),
 (262, 0.10650358071057624),
 (1166, 0.10619884881071831),
 (1501, 0.10619884881071831),
 (1745, 0.10619884881071831),
 (2161, 0.10619884881071831),
 (2634, 0.10619884881071831),
 (4135, 0.10619884881071831),
 (467, 0.10559715077387793),
 (541, 0.10559715077387793),
 (1496, 0.10559715077387793),
 (131, 0.10526315789473685),
 (295, 0.10526315789473685),
 (2072, 0.10526315789473685),
 (3340, 0.10526315789473685),
 (2498, 0.10471347707292386),
 (75, 0.10390486669322622),
 (223, 0.10390486669322622),
 (687, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1195, 0.10390486669322622),
 (1771, 0.10390486669322622),
 (2817, 0.10390486669322622),
 (654, 0.10385162309931599),
 (2439, 0.10385162309931599),
 (105, 0.1037571695799112),
 (233, 0.1037571695799112),
 (624, 0.1037571695799112),
 (2323, 0.1037571695799112),
 (2456, 0.1037571695799112),
 (2521, 0.1037571695799112),
 (3055, 0.1037571695799112),
 (3621, 0.1037571695799112),
 (3839, 0.1037571695799112),
 (1455, 0.10301070542879115),
 (10, 0.10259783520851541),
 (1082, 0.10259783520851541),
 (3152, 0.10259783520851541),
 (3634, 0.10259783520851541),
 (3755, 0.10259783520851541),
 (3874, 0.10259783520851541),
 (4097, 0.10259783520851541),
 (2106, 0.10218988991416095),
 (2762, 0.10147651372376076),
 (3663, 0.10147651372376076),
 (3954, 0.10147651372376076),
 (3441, 0.10138838820672659),
 (508, 0.101338918387628),
 (1294, 0.101338918387628),
 (2247, 0.10133891838762799),
 (1405, 0.10060545457319173),
 (1439, 0.10060545457319173),
 (2099, 0.10060545457319173),
 (312, 0.10012523486435178),
 (330, 0.10012523486435178),
 (643, 0.10012523486435178),
 (988, 0.10012523486435178),
 (1037, 0.10012523486435178),
 (1614, 0.10012523486435178),
 (35, 0.09933992677987831),
 (157, 0.09933992677987831),
 (319, 0.09933992677987831),
 (325, 0.09933992677987831),
 (715, 0.09933992677987831),
 (1077, 0.09933992677987831),
 (1280, 0.09933992677987831),
 (1884, 0.09933992677987831),
 (2053, 0.09933992677987831),
 (4018, 0.09933992677987831),
 (4198, 0.09933992677987831),
 (4490, 0.09933992677987831),
 (363, 0.09909250441117726),
 (491, 0.09909250441117726),
 (266, 0.0989541391990587),
 (445, 0.0989541391990587),
 (510, 0.0989541391990587),
 (3620, 0.0989541391990587),
 (3783, 0.0989541391990587),
 (3935, 0.0989541391990587),
 (1775, 0.09836118442057921),
 (410, 0.0978231976089037),
 (480, 0.0978231976089037),
 (535, 0.0978231976089037),
 (898, 0.0978231976089037),
 (1109, 0.0978231976089037),
 (1401, 0.0978231976089037),
 (1823, 0.0978231976089037),
 (2253, 0.0978231976089037),
 (33, 0.09733285267845754),
 (148, 0.09733285267845754),
 (263, 0.09733285267845754),
 (878, 0.09733285267845754),
 (1156, 0.09733285267845754),
 (1727, 0.09733285267845754),
 (1942, 0.09733285267845754),
 (2787, 0.09733285267845754),
 (4256, 0.09733285267845754),
 (4403, 0.09733285267845754),
 (4472, 0.09733285267845754),
 (9, 0.0967301666813349),
 (334, 0.0967301666813349),
 (371, 0.09567297464698798),
 (412, 0.09567297464698798),
 (2241, 0.09567297464698798),
 (2556, 0.09567297464698798),
 (4545, 0.09558988911273408),
 (362, 0.09544271444636668),
 (791, 0.09544271444636668),
 (1573, 0.09544271444636668),
 (2562, 0.09544271444636668),
 (4203, 0.09544271444636668),
 (18, 0.09493290614465533),
 (11, 0.09464970485606021),
 (587, 0.09464970485606021),
 (660, 0.09365858115816941),
 (920, 0.09365858115816941),
 (980, 0.09365858115816941),
 (1276, 0.09365858115816941),
 (1357, 0.09365858115816941),
 (1474, 0.09365858115816941),
 (1686, 0.09365858115816941),
 (1692, 0.09365858115816941),
 (1721, 0.09365858115816941),
 (2396, 0.09365858115816941),
 (2488, 0.09365858115816941),
 (2592, 0.09365858115816941),
 (2645, 0.09365858115816941),
 (2650, 0.09365858115816941),
 (2820, 0.09365858115816941),
 (3537, 0.09365858115816941),
 (3720, 0.09365858115816941),
 (4331, 0.09365858115816941),
 (4502, 0.09365858115816941),
 (301, 0.09365858115816939),
 (129, 0.09269795493186431),
 (243, 0.09269795493186431),
 (279, 0.09269795493186431),
 (473, 0.09269795493186431),
 (596, 0.09269795493186431),
 (813, 0.09269795493186431),
 (1446, 0.09269795493186431),
 (1701, 0.09269795493186431),
 (3407, 0.09269795493186431),
 (785, 0.09243423333081695),
 (219, 0.09197090092274487),
 (244, 0.09197090092274487),
 (511, 0.09197090092274487),
 (1756, 0.09197090092274487),
 (2093, 0.09197090092274487),
 (2651, 0.09197090092274487),
 (3736, 0.09197090092274487),
 (230, 0.09183979479633063),
 (799, 0.09183979479633063),
 (239, 0.09125667909262308),
 (2570, 0.09125667909262308),
 (43, 0.09086217008485092),
 (602, 0.09086217008485092),
 (997, 0.09086217008485092),
 (1233, 0.09086217008485092),
 (1846, 0.09086217008485092),
 (3881, 0.09086217008485092),
 (12, 0.09037128496931669),
 (88, 0.09037128496931669),
 (167, 0.09037128496931669),
 (356, 0.09037128496931669),
 (400, 0.09037128496931669),
 (1306, 0.09037128496931669),
 (1480, 0.09037128496931669),
 (2251, 0.09037128496931669),
 (2957, 0.09037128496931669),
 (331, 0.08998425413316952),
 (2363, 0.08998425413316952),
 (2796, 0.08998425413316952),
 (2856, 0.08998425413316952),
 (3389, 0.08998425413316952),
 (3443, 0.08998425413316952),
 (3462, 0.08998425413316952),
 (4343, 0.08998425413316952),
 (4353, 0.08998425413316952),
 (274, 0.08977310580745099),
 (1906, 0.0891313035643173),
 (2115, 0.08903057122447033),
 (292, 0.08885233166386385),
 (564, 0.08885233166386385),
 (1027, 0.08885233166386385),
 (2660, 0.08885233166386385),
 (2868, 0.08885233166386385),
 (3322, 0.08885233166386385),
 (169, 0.08830215713766959),
 (270, 0.08830215713766959),
 (618, 0.08830215713766959),
 (1783, 0.08830215713766959),
 (2109, 0.08830215713766959),
 (2713, 0.08830215713766959),
 (2740, 0.08830215713766959),
 (3553, 0.08830215713766959),
 (479, 0.08797691788472337),
 (752, 0.08749572785196143),
 (1832, 0.08749572785196143),
 (2448, 0.08746392856766495),
 (23, 0.08740748201220976),
 (141, 0.08740748201220976),
 (389, 0.08740748201220976),
 (745, 0.08740748201220976),
 (794, 0.08740748201220976),
 (960, 0.08740748201220976),
 (1249, 0.08740748201220976),
 (1259, 0.08740748201220976),
 (3448, 0.08740748201220976),
 (3449, 0.08740748201220976),
 (143, 0.08671099695241201),
 (199, 0.08671099695241201),
 (827, 0.08671099695241201),
 (1530, 0.08671099695241201),
 (2880, 0.08671099695241201),
 (3556, 0.08671099695241201),
 (4516, 0.08671099695241201),
 (4587, 0.08671099695241201),
 (2, 0.08603090020146065),
 (457, 0.08603090020146065),
 (775, 0.08603090020146065),
 (1378, 0.08603090020146065),
 (2583, 0.08603090020146065),
 (3135, 0.08603090020146065),
 (4754, 0.08603090020146065),
 (234, 0.08594700851870801),
 (1019, 0.08594700851870801),
 (2354, 0.08594700851870801),
 (32, 0.08520286456846099),
 (217, 0.08520286456846099),
 (142, 0.08471737420873576),
 (894, 0.08471737420873576),
 (1097, 0.08471737420873576),
 (1142, 0.08471737420873576),
 (1589, 0.08471737420873576),
 (2304, 0.08471737420873576),
 (4560, 0.08471737420873576),
 (48, 0.08447772061910234),
 (190, 0.08447772061910234),
 (1305, 0.08447772061910234),
 (1639, 0.08447772061910234),
 (2968, 0.08447772061910234),
 (62, 0.0837707816583391),
 (381, 0.0837707816583391),
 (534, 0.0837707816583391),
 (1698, 0.0837707816583391),
 (3180, 0.0837707816583391),
 (3218, 0.0837707816583391),
 (3978, 0.0837707816583391),
 (4737, 0.0837707816583391),
 (1, 0.08346223261119858),
 (152, 0.08346223261119858),
 (203, 0.08346223261119858),
 (315, 0.08346223261119858),
 (547, 0.08346223261119858),
 (1688, 0.08346223261119858),
 (2128, 0.08346223261119858),
 (2386, 0.08321783316232578),
 (19, 0.0830812984794528),
 (403, 0.0830812984794528),
 (3905, 0.0830812984794528),
 (45, 0.08240856434303293),
 (2203, 0.08240856434303293),
 (39, 0.08226127456606226),
 (227, 0.08226127456606226),
 (341, 0.08226127456606226),
 (626, 0.08226127456606226),
 (787, 0.08226127456606226),
 (1207, 0.08226127456606226),
 (1749, 0.08226127456606226),
 (2167, 0.08226127456606226),
 (2661, 0.08226127456606226),
 (3140, 0.08226127456606226),
 (3301, 0.08226127456606226),
 (3470, 0.08226127456606226),
 (63, 0.08175191193132876),
 (501, 0.08175191193132876),
 (38, 0.08111071056538127),
 (242, 0.08111071056538127),
 (245, 0.08111071056538127),
 (306, 0.08111071056538127),
 (584, 0.08111071056538127),
 (812, 0.08111071056538127),
 (866, 0.08111071056538127),
 (901, 0.08111071056538127),
 (1269, 0.08111071056538127),
 (1519, 0.08111071056538127),
 (1664, 0.08111071056538127),
 (2339, 0.08111071056538127),
 (2644, 0.08111071056538127),
 (2671, 0.08111071056538127),
 (2865, 0.08111071056538127),
 (2877, 0.08111071056538127),
 (3527, 0.08111071056538127),
 (3926, 0.08111071056538127),
 (4492, 0.08111071056538127),
 (4568, 0.08111071056538127),
 (4626, 0.08111071056538127),
 (4641, 0.08111071056538127),
 (4654, 0.08111071056538127),
 (4657, 0.08111071056538127),
 (51, 0.08048436365855338),
 (164, 0.08000711205939975),
 (854, 0.08000711205939975),
 (899, 0.08000711205939975),
 (1325, 0.08000711205939975),
 (1747, 0.08000711205939975),
 (2683, 0.08000711205939975),
 (3764, 0.08000711205939975),
 (3816, 0.08000711205939975),
 (3851, 0.08000711205939975),
 (486, 0.07992075789278003),
 (103, 0.07987230638308718),
 (222, 0.07987230638308718),
 (1534, 0.07987230638308718),
 (2792, 0.07987230638308718),
 (4506, 0.07987230638308718),
 (1898, 0.0792740035289418),
 (16, 0.07894736842105264),
 (37, 0.07894736842105264),
 (241, 0.07894736842105264),
 (329, 0.07894736842105264),
 (1080, 0.07894736842105264),
 (1161, 0.07894736842105264),
 (2295, 0.07894736842105264),
 (3233, 0.07894736842105264),
 (4316, 0.07894736842105264),
 (193, 0.07878168645790681),
 (153, 0.07868894753646337),
 (776, 0.07868894753646337),
 (1045, 0.07868894753646337),
 (1828, 0.07868894753646337),
 (1926, 0.07868894753646337),
 (3728, 0.07868894753646337),
 (3832, 0.07868894753646337),
 (4279, 0.07868894753646337),
 (4473, 0.07868894753646337),
 (125, 0.07843304784240032),
 (286, 0.0781166566864507),
 (1659, 0.0781166566864507),
 (174, 0.07792865001991967),
 (402, 0.07792865001991967),
 (922, 0.07792865001991967),
 (1113, 0.07792865001991967),
 (2938, 0.07792865001991967),
 (3028, 0.07792865001991967),
 (3091, 0.07792865001991967),
 (3102, 0.07792865001991967),
 (3164, 0.07792865001991967),
 (4341, 0.07792865001991967),
 (1924, 0.07755667343294813),
 (3560, 0.07755667343294813),
 (1282, 0.0770085628656519),
 (40, 0.07694837640638656),
 (96, 0.07694837640638656),
 (101, 0.07694837640638656),
 (112, 0.07694837640638656),
 (207, 0.07694837640638656),
 (632, 0.07694837640638656),
 (737, 0.07694837640638656),
 (1289, 0.07694837640638656),
 (2219, 0.07694837640638656),
 (4268, 0.07694837640638656),
 (4624, 0.07694837640638656),
 (850, 0.07647191129018727),
 (1005, 0.07647191129018727),
 (1139, 0.07647191129018727),
 (1254, 0.07647191129018727),
 (1621, 0.07647191129018727),
 (2165, 0.07647191129018727),
 (2274, 0.07647191129018727),
 (2712, 0.07647191129018727),
 (3430, 0.07647191129018727),
 (4165, 0.07647191129018727),
 (70, 0.076004188790721),
 (82, 0.076004188790721),
 (235, 0.076004188790721),
 (349, 0.076004188790721),
 (492, 0.076004188790721),
 (1290, 0.076004188790721),
 (1523, 0.076004188790721),
 (2449, 0.076004188790721),
 (2916, 0.076004188790721),
 (4558, 0.076004188790721),
 (246, 0.07594632491572426),
 (2005, 0.07543142864047142),
 (3331, 0.07530940414109724),
 (98, 0.07509392614826384),
 (210, 0.07509392614826384),
 (361, 0.07509392614826384),
 (365, 0.07509392614826384),
 (503, 0.07509392614826384),
 (540, 0.07509392614826384),
 (680, 0.07509392614826384),
 (1009, 0.07509392614826384),
 (1293, 0.07509392614826384),
 (2163, 0.07509392614826384),
 (4045, 0.07509392614826384),
 (4205, 0.07509392614826384),
 (2256, 0.07492686492653551),
 (205, 0.07443229275647868),
 (800, 0.07443229275647868),
 (995, 0.07443229275647868),
 (1323, 0.07443229275647868),
 (1521, 0.07443229275647868),
 (1770, 0.07443229275647868),
 (2326, 0.07443229275647868),
 (2551, 0.07443229275647868),
 (2801, 0.07443229275647868),
 (3069, 0.07443229275647868),
 (3117, 0.07443229275647868),
 (3126, 0.07443229275647868),
 (4011, 0.07443229275647868),
 (4412, 0.07443229275647868),
 (4542, 0.07443229275647868),

In [69]:
#Now sortout top 5 movies from the list

sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [70]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]           #fetched the index
    distances = similarity[movie_index]                        #find the distances of movie index
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(df.iloc[i[0]].title)    #Because the system recommend title of the movie not a index of the title

In [71]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [72]:
recommend('John Carter')

Riddick
Krrish
The Other Side of Heaven
The Legend of Hercules
Get Carter

In [73]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

#### According to the function the recommendation system is working fine.